openapi: 3.0.0
info:
  title: Partner API
  version: '1.0'
  description: Partner API to create and manage orders
  contact:
    name: LoadUp Engineering
    email: engineering@goloadup.com
    url: goloadup.com
servers:
  - url: order.goloadup.com/partner/api
    description: Production
paths:
  /orders:
    get:
      summary: Your GET endpoint
      tags:
        - fooey
      responses:
        '200':
          description: OK
        '201':
          description: Created
      operationId: get-orders
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      parameters:
        - schema:
            type: number
          in: query
          name: order-id
          description: ''
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      name: API Key
      type: apiKey
      in: header
