openapi: 3.0.0
info:
  title: Partner API
  version: '1.0'
  description: Partner API to create and manage orders
  contact:
    name: LoadUp Engineering
    email: engineering@goloadup.com
    url: goloadup.com
servers:
  - url: order.goloadup.com/partner/api
    description: Production
paths:
  /orders:
    post:
      summary: ''
      operationId: post-orders
      responses:
        '200':
          description: OK
          headers:
            header-0:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  '':
                    type: string
      description: Foeey dee blah di blah I am
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                order:
                  $ref: '#/components/schemas/Order'
        description: Send details about order
components:
  schemas:
    Order:
      title: Order
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        location:
          type: object
          properties:
            latitude:
              type: string
      x-examples:
        'success ':
          firstName: John
      description: ''
  securitySchemes:
    API Key - 1:
      name: API Key
      type: apiKey
      in: header
